#!/bin/bash

  REPORT_DIR="build/hook"
rm -rf $REPORT_DIR || true
mkdir -p ${REPORT_DIR}
PIDSTOOUTPUTFILES=()
TASK_FILE_GRADLEW=${REPORT_DIR}/gradlew.log
./gradlew lint assemble test assembleAndroidTest > $TASK_FILE_GRADLEW 2>&1 &
PIDSTOOUTPUTFILES+=("$!:$TASK_FILE_GRADLEW")

TASK_FILE_KTLINT=${REPORT_DIR}/ktlint.log
./run-ktlint.sh > $TASK_FILE_KTLINT 2>&1 &
PIDSTOOUTPUTFILES+=("$!:$TASK_FILE_KTLINT")

  TASK_FILE_DETEKT=${REPORT_DIR}/detekt.log
./run-detekt.sh > $TASK_FILE_DETEKT 2>&1 &
PIDSTOOUTPUTFILES+=("$!:$TASK_FILE_DETEKT")

  while :
do
 INDEX=-1
 for PIDTOOUTPUTFILE in "${PIDSTOOUTPUTFILES[@]}"; do
  INDEX=$INDEX+1
  PID=${PIDTOOUTPUTFILE%%:*}
  if ! ps -p "$PID" > /dev/null
  then
   if wait "$PID"; then
    unset 'PIDSTOOUTPUTFILES[$INDEX]'
    PIDSTOOUTPUTFILES=("${PIDSTOOUTPUTFILES[@]}")
    if [ ${#PIDSTOOUTPUTFILES[@]} -eq 0 ]; then
      exit 0
    fi
   else
    jobs -p | xargs kill
    cat "${PIDTOOUTPUTFILE#*:}"
    exit 1
   fi
  fi
 done
 sleep 1
done
